In [21]:
import pandas as pd

In [22]:
df_eventos = pd.read_csv("output/distancias_20160415.csv")

In [23]:
df_eventos.tail(5)

,Index,FechaEvento,Hora,ProvinciaCliente,CantonCliente,CiudadCliente,ParroquiaCliente,LatitudCliente,LongitudCliente,NombreSitioEvento,...,ParroquiaEvento,LatitudEvento,LongitudEvento,ID,BaseCliente,BaseEvento,CantidadClientes,GeoIdCliente,GeoIdEvento,Distancia
199748,199748,2016-04-15,23,TUNGURAHUA,PATATE,PATATE,PATATE,-1.30875,-78.5062,IESS_PORTOVIEJO,...,PORTOVIEJO,-1.047240,-80.4718,8748980,45226,99990,2,854,489,220.666288
199749,199749,2016-04-15,23,TUNGURAHUA,QUERO,YANAYACU - MOCHAPATA (CAB. EN YANAYACU),YANAYACU - MOCHAPATA (CAB. EN YANAYACU),-1.44017,-78.6674,CDLA_AURORA,...,MANTA,-0.981686,-80.7053,429177,20350,50064,1,1145,418,232.403967
199750,199750,2016-04-15,23,TUNGURAHUA,SAN PEDRO DE PELILEO,GARCIA MORENO (CHUMAQUI),GARCIA MORENO (CHUMAQUI),-1.32751,-78.5556,PEDERNALES_PLAYA,...,PEDERNALES,0.071642,-80.0548,1662318,20696,21159,1,910,468,227.558690
199751,199751,2016-04-15,23,TUNGURAHUA,SAN PEDRO DE PELILEO,GARCIA MORENO (CHUMAQUI),GARCIA MORENO (CHUMAQUI),-1.32001,-78.5331,EL_CARMEN_MANABI,...,EL CARMEN,-0.272244,-79.4577,1179017,39222,16127,1,1317,399,154.964839
199752,199752,2016-04-15,23,TUNGURAHUA,SAN PEDRO DE PELILEO,GARCIA MORENO (CHUMAQUI),GARCIA MORENO (CHUMAQUI),-1.32001,-78.5331,SAN_PEDRO_DE_SUMA,...,SAN PEDRO DE SUMA,-0.219281,-79.5417,3999605,39222,17475,1,1317,400,165.581984

In [24]:
df_working_hours = df_eventos[(df_eventos["Hora"]>6) & (df_eventos["Hora"]<23)]
df_working_hours = df_working_hours.drop("Index", axis=1)

In [25]:
df_working_hours.shape

(160440, 22)

In [26]:
df_working_hours.head(1)

,FechaEvento,Hora,ProvinciaCliente,CantonCliente,CiudadCliente,ParroquiaCliente,LatitudCliente,LongitudCliente,NombreSitioEvento,ProvinciaEvento,...,ParroquiaEvento,LatitudEvento,LongitudEvento,ID,BaseCliente,BaseEvento,CantidadClientes,GeoIdCliente,GeoIdEvento,Distancia
32175,2016-04-15,7,AZUAY,CAMILO PONCE ENRIQUEZ,CAMILO PONCE ENRIQUEZ,CAMILO PONCE ENRIQUEZ,-3.05086,-79.7285,BAHIA,MANABI,...,BAHIA DE CARAQUEZ,-0.617236,-80.4367,4111890,41164,17507,1,1,505,280.396885

In [27]:
df_working_hours.to_csv("output/working_hours_20160415.csv", index=True)